#  Template NodeJS build
#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.
image: node:16 # Choose an image matching your project needs
clone:
  depth: full # SonarCloud scanner needs the full history to assign issues properly
definitions:
  caches:
    sonar: ~/.sonar/cache # Caching SonarCloud artifacts will speed up your build
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        caches:
          - node
        script:
          - yarn install
          - yarn test
          - pipe: sonarsource/sonarcloud-scan:1.4.0
    # - step: &check-quality-gate-sonarcloud
    #     name: Check the Quality Gate on SonarCloud
    #     script:
    #       - pipe: sonarsource/sonarcloud-quality-gate:0.1.6
pipelines: # More info here: https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html
  branches:
    jest-test:
      - step: *build-test-sonarcloud
      # - step: *check-quality-gate-sonarcloud
  pull-requests:
    '**':
      - step: *build-test-sonarcloud
      # - step: *check-quality-gate-sonarcloud
